from src.pokemon import *
import pytest

def test_speed():
    assert speed() == {'45': 9, '60': 8, '80': 6, '65': 6, '100': 9, '43': 1, '58': 1, '78': 2, '30': 6, '70': 10, '50': 6, '35': 6, '75': 3, '145': 1, '56': 2, '71': 1, '101': 1, '121': 1, '72': 1, '97': 1, '55': 7, '90': 10, '110': 3, '40': 6, '41': 1, '76': 2, '85': 5, '20': 2, '25': 3, '95': 5, '120': 2, '115': 2, '105': 5, '150': 1, '15': 1, '130': 2, '42': 1, '67': 1, '140': 1, '87': 1, '63': 1, '68': 1, '93': 1, '81': 2, '48': 1}

def test_pokemon_types():
    assert pokemon_types(None) == {'Grass': ['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur', 'Oddish', 'Gloom', 'Vileplume', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Exeggcute', 'Exeggutor', 'Tangela'], 'Fire': ['Charmander', 'Charmeleon', 'Charizard', 'CharizardMega Charizard X', 'CharizardMega Charizard Y', 'Vulpix', 'Ninetales', 'Growlithe', 'Arcanine', 'Ponyta', 'Rapidash', 'Magmar', 'Flareon'], 'Water': ['Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise', 'Psyduck', 'Golduck', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Tentacool', 'Tentacruel', 'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Seel', 'Dewgong', 'Shellder', 'Cloyster', 'Krabby', 'Kingler', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Magikarp', 'Gyarados', 'GyaradosMega Gyarados', 'Lapras', 'Vaporeon'], 'Bug': ['Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'BeedrillMega Beedrill', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Scyther', 'Pinsir', 'PinsirMega Pinsir'], 'Normal': ['Pidgey', 'Pidgeotto', 'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Jigglypuff', 'Wigglytuff', 'Meowth', 'Persian', "Farfetch'd", 'Doduo', 'Dodrio', 'Lickitung', 'Chansey', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Tauros', 'Ditto', 'Eevee'], 'Poison': ['Ekans', 'Arbok', 'Nidoranâ™€', 'Nidorina', 'Nidoqueen', 'Nidoranâ™‚', 'Nidorino', 'Nidoking', 'Zubat', 'Golbat', 'Grimer', 'Muk', 'Koffing', 'Weezing'], 'Electric': ['Pikachu', 'Raichu', 'Magnemite', 'Magneton', 'Voltorb', 'Electrode', 'Electabuzz', 'Jolteon'], 'Ground': ['Sandshrew', 'Sandslash', 'Diglett', 'Dugtrio', 'Cubone', 'Marowak', 'Rhyhorn', 'Rhydon'], 'Fairy': ['Clefairy', 'Clefable'], 'Fighting': ['Mankey', 'Primeape', 'Machop', 'Machoke', 'Machamp', 'Hitmonlee', 'Hitmonchan'], 'Psychic': ['Abra', 'Kadabra', 'Alakazam', 'AlakazamMega Alakazam', 'Drowzee', 'Hypno', 'Mr. Mime'], 'Rock': ['Geodude', 'Graveler', 'Golem', 'Onix'], 'Ghost': ['Gastly', 'Haunter', 'Gengar', 'GengarMega Gengar'], 'Ice': ['Jynx']}

